name: 'DEV DEPLOY'

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      environment: dev
